version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
